name = "tinygrad"
uuid = "f6bd70a2-8429-477d-b060-9e69ea4fdef3"
author = ["jmnoynaert@gmail.com"]
version = "0.1.0"

[deps]

[compat]
julia = "1.0"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "BenchmarkTools", "Zygote"]
